name: Webhook Logger

on:
  repository_dispatch:
    types: [update]

jobs:
  log-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log Webhook Payload
      run: |
        echo "Webhook Payload:"
        echo '${{ toJson(github.event.client_payload) }}' | jq .
      env:
        GITHUB_EVENT: ${{ toJson(github.event.client_payload) }}