name: Webhook Logger

on:
  repository_dispatch:
    types: [update]

jobs:
  log-webhook:
    runs-on: ubuntu-latest
    concurrency:
      group: production-build
      cancel-in-progress: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log Webhook Payload
      run: |
        echo "Full GitHub Event Data:" 
        echo '${{ toJson(github.event) }}' | jq .

        echo "Webhook Payload:"
        echo '${{ toJson(github.event.client_payload) }}' | jq .