name: Webhook Logger

on:
  workflow_dispatch: 
  push:              
  repository_dispatch:
    types: [microcms-webhook]

jobs:
  log-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log Webhook Payload
      run: |
        echo "Webhook Payload:"
        echo "${{ github.event.client_payload }}"